#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_manifest.py — manifest of the paper package: sha256 of every file that ships."""
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SKIP_DIRS = {'__pycache__'}
SKIP_EXT = {'.aux', '.out', '.log', '.toc'}
# These three files describe the package itself and are written after hashing: they do not
# include themselves in the manifest, or the check would always report three mismatches.
SELF = {'MANIFEST.sha256', 'ARTIFACTS.md', 'artifacts.json'}


def sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''):
            h.update(b)
    return h.hexdigest()


rows = []
for dp, dn, fn in os.walk(HERE):
    dn[:] = [d for d in dn if d not in SKIP_DIRS]
    for x in sorted(fn):
        p = os.path.join(dp, x)
        if os.path.splitext(x)[1] in SKIP_EXT or x in SELF:
            continue
        rows.append((os.path.relpath(p, HERE), os.path.getsize(p), sha(p)))
rows.sort()

lines = ['# MANIFEST — paper package', '',
         'Generated by `make_manifest.py`. Every file of the package, with its size and sha256.',
         'Check: `sha256sum -c MANIFEST.sha256`.', '',
         '| file | bytes | sha256 |', '|---|---|---|']
for rel, size, h in rows:
    lines.append('| `%s` | %d | `%s` |' % (rel, size, h))
lines.append('')
lines.append('Total files: %d.' % len(rows))
open(os.path.join(HERE, 'ARTIFACTS.md'), 'w').write('\n'.join(lines) + '\n')
with open(os.path.join(HERE, 'MANIFEST.sha256'), 'w') as f:
    for rel, size, h in rows:
        f.write('%s  %s\n' % (h, rel))
json.dump({rel: {'bytes': size, 'sha256': h} for rel, size, h in rows},
          open(os.path.join(HERE, 'artifacts.json'), 'w'), indent=1)
print('ARTIFACTS.md: %d files' % len(rows))
print('MANIFEST_OK')
